metrics:
  # System metrics
  system:
    path: "system"
    metrics:
      - name: "cpu_load"
        field: "cpuload"
        help: "CPU load percentage"
      - name: "memory_usage"
        field: "memory"
        help: "Current memory usage in KB"
      - name: "memory_total"
        field: "memtotal"
        help: "Total memory in KB"
      - name: "memory_free"
        field: "memfree"
        help: "Free memory in KB"
      - name: "memory_buffers"
        field: "membuffers"
        help: "Memory used by buffers in KB"
      - name: "memory_cache"
        field: "memcache"
        help: "Memory used by cache in KB"
      - name: "connections_total"
        field: "conntotal"
        help: "Total number of possible connections"
      - name: "connections_free"
        field: "connfree"
        help: "Number of free connections"

  # Interface metrics
  interface_usblte0:
    path: "interface/UsbLte0"
    metrics:
      - name: "signal_strength"
        field: "rssi"
        help: "LTE signal strength in dBm"
      - name: "signal_level"
        field: "signal-level"
        help: "LTE signal quality level (0-5)"
      - name: "rsrp"
        field: "rsrp"
        help: "Reference Signal Received Power in dBm"
      - name: "rsrq"
        field: "rsrq"
        help: "Reference Signal Received Quality in dB"
      - name: "cinr"
        field: "cinr"
        help: "Carrier to Interference plus Noise Ratio in dB"
      - name: "temperature"
        field: "temperature"
        help: "Modem temperature in Celsius"

  interface_usblte0_traffic:
    path: "interface/traffic-counter"
    params:
      name: "UsbLte0"
      noformat: true
    metrics:
      - name: "traffic_value"
        field: "value"
        help: "Current traffic usage in KiB"
      - name: "traffic_threshold"
        field: "threshold"
        help: "Traffic threshold in KiB"
      - name: "traffic_limit"
        field: "limit"
        help: "Traffic limit in KiB"
      - name: "traffic_remaining"
        field: "remaining"
        help: "Remaining traffic in KiB"
      - name: "traffic_days_left"
        field: "days-left"
        help: "Days left in current period"

  # WiFi clients metrics
  hotspot_clients:
    path: "ip/hotspot"
    metrics:
      - name: "connected_clients_total"
        help: "Total number of connected clients"
        calculate: "length(host[?active===true])"

      - name: "client_uptime"
        help: "Client connection uptime in seconds"
        labels:
          - "mac"
          - "name"
          - "hostname"
        field: "uptime"
        array_selector: "host[?active===true]"

      - name: "client_received_bytes"
        help: "Total bytes received from client"
        labels:
          - "mac"
          - "name"
          - "hostname"
        field: "rxbytes"
        array_selector: "host"

      - name: "client_transmitted_bytes"
        help: "Total bytes transmitted to client"
        labels:
          - "mac"
          - "name"
          - "hostname"
        field: "txbytes"
        array_selector: "host"

      - name: "client_signal_strength"
        help: "Client signal strength in dBm"
        labels:
          - "mac"
          - "name"
          - "hostname"
        field: "rssi"
        array_selector: "host[?ssid]"
